SELECT GETDATE()

SELECT SYSDATETIME()

SELECT SYSUTCDATETIME() 

SELECT DATEFROMPARTS(2023,11,4) --YYYY-MM-DD format
-- Alternatively we can write it as SELECT '2023-11-04'

SELECT DATETIMEFROMPARTS(2023,11,4,8,15,45,200) --YYYY-MM-DD H:M:S:MS format

SELECT YEAR(GETDATE())

SELECT BirthDate, YEAR(BirthDate) FROM DimEmployee

SELECT MONTH(GETDATE())

SELECT BirthDate, MONTH(BirthDate) FROM DimEmployee

SELECT DAY(GETDATE())

SELECT BirthDate, DAY(BirthDate) FROM DimEmployee

SELECT DATEPART(YYYY,GETDATE())
SELECT DATEPART(MM,GETDATE())
SELECT DATEPART(DD,GETDATE())
SELECT DATEPART(WEEKDAY,GETDATE())
SELECT DATEPART(WEEK,GETDATE())

SELECT FORMAT(GETDATE(),'yy') -- only use lowercase
SELECT FORMAT(GETDATE(),'d') -- will not work for days above 9
SELECT FORMAT(GETDATE(),'M') -- here we have to use upper case
SELECT FORMAT(GETDATE(),'hh')
SELECT FORMAT(GETDATE(),'mm')
SELECT FORMAT(GETDATE(),'dd-MM-yyyy hh:mm:ss')